name: Python application
env:
  VARWFLVL: 'testvar'

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2
    - name: print var
      run: |
        echo "---"
        echo "${{ env.VARWFLVL }}"
        echo "---"
    - name: Python Syntax Checker
      uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_FAKE_API }}
